..\..\win\webpmux.exe -get frame  1 butterfly.webp -o ..\cwebp\butterfly\bf001.webp
..\..\win\webpmux.exe -get frame  2 butterfly.webp -o ..\cwebp\butterfly\bf002.webp
..\..\win\webpmux.exe -get frame  3 butterfly.webp -o ..\cwebp\butterfly\bf003.webp
..\..\win\webpmux.exe -get frame  4 butterfly.webp -o ..\cwebp\butterfly\bf004.webp
..\..\win\webpmux.exe -get frame  5 butterfly.webp -o ..\cwebp\butterfly\bf005.webp
..\..\win\webpmux.exe -get frame  6 butterfly.webp -o ..\cwebp\butterfly\bf006.webp
..\..\win\webpmux.exe -get frame  7 butterfly.webp -o ..\cwebp\butterfly\bf007.webp
..\..\win\webpmux.exe -get frame  8 butterfly.webp -o ..\cwebp\butterfly\bf008.webp
..\..\win\webpmux.exe -get frame  9 butterfly.webp -o ..\cwebp\butterfly\bf009.webp
..\..\win\webpmux.exe -get frame 10 butterfly.webp -o ..\cwebp\butterfly\bf010.webp
..\..\win\webpmux.exe -get frame 11 butterfly.webp -o ..\cwebp\butterfly\bf011.webp
..\..\win\webpmux.exe -get frame 12 butterfly.webp -o ..\cwebp\butterfly\bf012.webp
..\..\win\webpmux.exe -get frame 13 butterfly.webp -o ..\cwebp\butterfly\bf013.webp
..\..\win\webpmux.exe -get frame 14 butterfly.webp -o ..\cwebp\butterfly\bf014.webp
..\..\win\webpmux.exe -get frame 15 butterfly.webp -o ..\cwebp\butterfly\bf015.webp
..\..\win\webpmux.exe -get frame 16 butterfly.webp -o ..\cwebp\butterfly\bf016.webp
..\..\win\webpmux.exe -get frame 17 butterfly.webp -o ..\cwebp\butterfly\bf017.webp
..\..\win\webpmux.exe -get frame 18 butterfly.webp -o ..\cwebp\butterfly\bf018.webp
..\..\win\webpmux.exe -get frame 19 butterfly.webp -o ..\cwebp\butterfly\bf019.webp
..\..\win\webpmux.exe -get frame 20 butterfly.webp -o ..\cwebp\butterfly\bf020.webp
..\..\win\webpmux.exe -get frame 21 butterfly.webp -o ..\cwebp\butterfly\bf021.webp
..\..\win\webpmux.exe -get frame 22 butterfly.webp -o ..\cwebp\butterfly\bf022.webp
..\..\win\webpmux.exe -get frame 23 butterfly.webp -o ..\cwebp\butterfly\bf023.webp
..\..\win\webpmux.exe -get frame 24 butterfly.webp -o ..\cwebp\butterfly\bf024.webp
..\..\win\webpmux.exe -get frame 25 butterfly.webp -o ..\cwebp\butterfly\bf025.webp
..\..\win\webpmux.exe -get frame 26 butterfly.webp -o ..\cwebp\butterfly\bf026.webp
..\..\win\webpmux.exe -get frame 27 butterfly.webp -o ..\cwebp\butterfly\bf027.webp
..\..\win\webpmux.exe -get frame 28 butterfly.webp -o ..\cwebp\butterfly\bf028.webp
..\..\win\webpmux.exe -get frame 29 butterfly.webp -o ..\cwebp\butterfly\bf029.webp
..\..\win\webpmux.exe -get frame 30 butterfly.webp -o ..\cwebp\butterfly\bf030.webp
..\..\win\webpmux.exe -get frame 31 butterfly.webp -o ..\cwebp\butterfly\bf031.webp
..\..\win\webpmux.exe -get frame 32 butterfly.webp -o ..\cwebp\butterfly\bf032.webp
..\..\win\webpmux.exe -get frame 33 butterfly.webp -o ..\cwebp\butterfly\bf033.webp
..\..\win\webpmux.exe -get frame 34 butterfly.webp -o ..\cwebp\butterfly\bf034.webp
..\..\win\webpmux.exe -get frame 35 butterfly.webp -o ..\cwebp\butterfly\bf035.webp
..\..\win\webpmux.exe -get frame 36 butterfly.webp -o ..\cwebp\butterfly\bf036.webp
..\..\win\webpmux.exe -get frame 37 butterfly.webp -o ..\cwebp\butterfly\bf037.webp
..\..\win\webpmux.exe -get frame 38 butterfly.webp -o ..\cwebp\butterfly\bf038.webp
..\..\win\webpmux.exe -get frame 39 butterfly.webp -o ..\cwebp\butterfly\bf039.webp
..\..\win\webpmux.exe -get frame 40 butterfly.webp -o ..\cwebp\butterfly\bf040.webp
..\..\win\webpmux.exe -get frame 41 butterfly.webp -o ..\cwebp\butterfly\bf041.webp
..\..\win\webpmux.exe -get frame 42 butterfly.webp -o ..\cwebp\butterfly\bf042.webp
..\..\win\webpmux.exe -get frame 43 butterfly.webp -o ..\cwebp\butterfly\bf043.webp
..\..\win\webpmux.exe -get frame 44 butterfly.webp -o ..\cwebp\butterfly\bf044.webp
..\..\win\webpmux.exe -get frame 45 butterfly.webp -o ..\cwebp\butterfly\bf045.webp
..\..\win\webpmux.exe -get frame 46 butterfly.webp -o ..\cwebp\butterfly\bf046.webp
..\..\win\webpmux.exe -get frame 47 butterfly.webp -o ..\cwebp\butterfly\bf047.webp
..\..\win\webpmux.exe -get frame 48 butterfly.webp -o ..\cwebp\butterfly\bf048.webp
..\..\win\webpmux.exe -get frame 49 butterfly.webp -o ..\cwebp\butterfly\bf049.webp
..\..\win\webpmux.exe -get frame 50 butterfly.webp -o ..\cwebp\butterfly\bf050.webp
..\..\win\webpmux.exe -get frame 51 butterfly.webp -o ..\cwebp\butterfly\bf051.webp
..\..\win\webpmux.exe -get frame 52 butterfly.webp -o ..\cwebp\butterfly\bf052.webp
..\..\win\webpmux.exe -get frame 53 butterfly.webp -o ..\cwebp\butterfly\bf053.webp
..\..\win\webpmux.exe -get frame 54 butterfly.webp -o ..\cwebp\butterfly\bf054.webp
..\..\win\webpmux.exe -get frame 55 butterfly.webp -o ..\cwebp\butterfly\bf055.webp
..\..\win\webpmux.exe -get frame 56 butterfly.webp -o ..\cwebp\butterfly\bf056.webp
..\..\win\webpmux.exe -get frame 57 butterfly.webp -o ..\cwebp\butterfly\bf057.webp
..\..\win\webpmux.exe -get frame 58 butterfly.webp -o ..\cwebp\butterfly\bf058.webp
..\..\win\webpmux.exe -get frame 59 butterfly.webp -o ..\cwebp\butterfly\bf059.webp
..\..\win\webpmux.exe -get frame 60 butterfly.webp -o ..\cwebp\butterfly\bf060.webp
..\..\win\webpmux.exe -get frame 61 butterfly.webp -o ..\cwebp\butterfly\bf061.webp
..\..\win\webpmux.exe -get frame 62 butterfly.webp -o ..\cwebp\butterfly\bf062.webp
..\..\win\webpmux.exe -get frame 63 butterfly.webp -o ..\cwebp\butterfly\bf063.webp
..\..\win\webpmux.exe -get frame 64 butterfly.webp -o ..\cwebp\butterfly\bf064.webp
..\..\win\webpmux.exe -get frame 65 butterfly.webp -o ..\cwebp\butterfly\bf065.webp
..\..\win\webpmux.exe -get frame 66 butterfly.webp -o ..\cwebp\butterfly\bf066.webp
..\..\win\webpmux.exe -get frame 67 butterfly.webp -o ..\cwebp\butterfly\bf067.webp
